DELETE FROM simeialv_ongcontrol.doacaoeventopessoa;
DELETE FROM simeialv_ongcontrol.doacaoevento;
DELETE FROM simeialv_ongcontrol.pessoaevento;
DELETE FROM simeialv_ongcontrol.tipocolaboradorevento;
DELETE FROM simeialv_ongcontrol.tipodoacaoevento;