name: Deploy to Elastic Beanstalk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Deploy to Elastic Beanstalk - ONGControlServer
        run: |
          npm install
          cd server
          zip -r ongcontrolweb-server.zip *
          aws s3 cp ongcontrolweb-server.zip s3://elasticbeanstalk-us-east-1-166115332584/ongcontrolweb-server.zip
          aws elasticbeanstalk create-application-version --application-name ongcontrol-server --version-label $GITHUB_SHA --source-bundle S3Bucket="elasticbeanstalk-us-east-1-166115332584",S3Key="ongcontrolweb-server.zip"
          aws elasticbeanstalk update-environment --environment-name Ongcontrolserver-env --version-label $GITHUB_SHA
      - name: Deploy to Elastic Beanstalk - ONGControlClient
        run: |
          npm install
          cd ..
          cd client
          zip -r ongcontrolweb-client.zip *
          aws s3 cp ongcontrolweb-client.zip s3://elasticbeanstalk-us-east-1-166115332584/ongcontrolweb-client.zip
          aws elasticbeanstalk create-application-version --application-name ongcontrol-client --version-label $GITHUB_SHA --source-bundle S3Bucket="elasticbeanstalk-us-east-1-166115332584",S3Key="ongcontrolweb-client.zip"
          aws elasticbeanstalk update-environment --environment-name Ongcontrolclient-env --version-label $GITHUB_SHA
