name: Deploy to Elastic Beanstalk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Build and deploy to Elastic Beanstalk
        run: |
          npm install
          npm run build
          zip -r my-app-$GITHUB_SHA.zip .
          aws elasticbeanstalk create-application-version --application-name my-app --version-label $GITHUB_SHA --source-bundle S3Bucket=elasticbeanstalk-us-east-1-1234567890,S3Key=my-app-$GITHUB_SHA.zip
          aws elasticbeanstalk update-environment --environment-name my-env --version-label $GITHUB_SHA
