name: Deploy to Elastic Beanstalk - Client
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Build and package frontend
        env:
          ENVIRONMENT_NAME: "Client11-env"
          APPLICATION_NAME: "client11"
          FILE_ZIP: "ongcontrolweb-client.zip"
          BUCKET_S3_NAME: "elasticbeanstalk-us-east-1-166115332584"
        run: |
          cd client
          npm install
          npm run build
          aws s3 sync build/ s3://$BUCKET_S3_NAME --delete
          aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $GITHUB_SHA --source-bundle S3Bucket=$BUCKET_S3_NAME,S3Key=$FILE_ZIP
          aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_SHA
