name: Deploy to Elastic Beanstalk - Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Deploy to Elastic Beanstalk - ONGControlServer
        run: |
          set $environment_name=Ongcontrolwebserver-env
          set $application_name=ongcontrolweb-server
          set $filezip=ongcontrolweb-server.zip
          set $buckets3_name=elasticbeanstalk-us-east-1-166115332584
          npm install
          cd server
          zip -r %filezip% *
          aws s3 cp %filezip% s3://%buckets3_name%/%filezip%
          aws elasticbeanstalk create-application-version --application-name %application_name% --version-label $GITHUB_SHA --source-bundle S3Bucket="%buckets3_name%",S3Key="%filezip%"
          aws elasticbeanstalk update-environment --environment-name %environment_name% --version-label $GITHUB_SHA
